version: '3'
services:

  forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --proxy.bind=:8443
      --proxy.upstream-url=http://superproxy.com:8080
      --proxy.user=
      --proxy.pass=
      --filter.zones=api.ipify.org
      --exclude.hostnames=ipify.org
    cap_add:
    - NET_ADMIN
    - NET_RAW
    ports:
    - "8443:8443"